### ISSUE TITLE
run consul/vault co-located or dedicated

### ISSUE THREAD

**Issue by gthieleb** [Kreditorforeningens-Driftssentral-DA/ansible-collection-hashicluster#7]
First thanks to this great approach for setup a full nomad environment with consul/vault enabled.
Short question: Is it possible using this role to have the consul service co-located but the vault service to run on different cluster nodes?

**Comment by kds-rune** [comment]
It should work any way you configure it. You can install any or none of the applications on any node.
You just set the "install" flag for each application you want to install on the node(s) (defaults to "false" for all of the applications):

```yaml
- hosts: somehosts
  tasks:
  - name: "Role: HashiCluster (Nomad/Consul)"
    include_role:
      name: hashicluster
    vars:
      dns:
        forward: true
      cluster:
        consul:
          install: true
          config: {}
        nomad:
          install: true
          config: {}

- hosts: otherhosts
  tasks:
  - name: "Role: HashiCluster (Vault)"
    include_role:
      name: hashicluster
    vars:
      dns:
        forward: true
      cluster:
        vault:
          install: true
```

(I strayed away from using this role myself, since I was experimenting using cloud-init, and it was easier in my case at the time just writing a bash-script. I will try to revise this role when I find the time, and also try to add in some more configuration examples.)
