### ISSUE TITLE
question about nomad post configuration

### ISSUE THREAD

**Issue by gthieleb** [Kreditorforeningens-Driftssentral-DA/ansible-collection-hashicluster#8]
I am currently looking for further configuration of nomad especially the parts about consul integration and nomad integration. Can you point me to the configuration parts? Thanks a lot.

**Comment by kds-rune** [comment]
Hi! Sorry; I somehow missed notifications on these issues.

The configurations are added as yaml, and converted to json (since only hcl & json are accepted by the applications). This is done so I don't have to maintain any jinja2-templates (the nomad/consul/vault config-entries change from time to time, and this way I don't have to maintain anything).

The yaml indentation follows the syntax from the official documentations. E.g. for the example show on the [consul](https://www.nomadproject.io/docs/configuration/consul)-section section for nomad (top level config entry), the syntax in this collection/role would be:

```hcl
# HCL entry
consul {
  address = "127.0.0.1:8500"
  auth    = "admin:password"
  token   = "abcd1234"
}
```
```yaml
# role/yaml-entry
 - name: Install Cluster applications
    include_role:
      name: hashicluster
    vars:
      cluster:
        nomad:
          consul:
            address: "127.0.0.1:8500"
            auth: "admin:password"
            token: "abcd1234"
```
